In [2]:
import pandas as pd

all_job_post = pd.read_csv("C:\\Users\\Lamees\\Downloads\\all_job_post.csv")
all_job_post.head()

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,3905834061,HR,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm..."
4,3906250451,HR,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe..."

In [3]:
import pandas as pd

fact_job_postings = pd.read_csv("C:\\Users\\Lamees\\Downloads\\fact_job_postings.csv")
fact_job_postings.head()

,job_id,job_title,company,country,region,platform,experience_level,employment_type,salary_min_usd,salary_max_usd,remote_option,posting_date,applicants_estimate
0,JOB-1,Senior Data Engineer,Netflix,Spain,Europe,Wellfound,Lead,Part-time,163731,171017,Hybrid,52:59.3,472
1,JOB-2,Data Engineer,Snowflake,India,Asia,Indeed,Mid,Contract,145213,153462,Hybrid,52:59.3,500
2,JOB-3,Business Intelligence Analyst,IBM,Netherlands,Europe,Monster,Entry,Contract,87206,121991,Onsite,52:59.3,34
3,JOB-4,Data Scientist,Nvidia,Netherlands,Europe,Indeed,Lead,Full-time,104392,130952,Remote,52:59.3,26
4,JOB-5,AI Engineer,Netflix,Germany,Europe,Company Site,Mid,Part-time,162767,186131,Hybrid,52:59.3,303

In [4]:
import pandas as pd

global_ai_ml_jobs_2025 = pd.read_csv("C:\\Users\\Lamees\\Downloads\\global_ai_ml_jobs_2025.csv")
global_ai_ml_jobs_2025.head()

,Year,Job Title,Experience Level,Employment Type,Company Size,Work Setting,Country,Salary (USD),Skills
0,2024,Prompt Engineer,Entry-level,Full-time,Medium,Remote,Germany,49000.0,"PyTorch, OpenCV, TensorFlow, Scala"
1,2025,Machine Learning Engineer,Mid-level,Full-time,Large,Remote,France,102900.0,"OpenCV, Scala, AWS, Java"
2,2024,Machine Learning Operations (MLOps) Engineer,Entry-level,Full-time,Small,On-site,Norway,63100.0,"Azure, Scikit-learn, Docker, LLMs, PyTorch"
3,2025,Machine Learning Engineer,Senior,Full-time,Large,Hybrid,China,155000.0,"Java, OpenCV, PyTorch"
4,2025,Computer Vision Engineer,Entry-level,Full-time,Large,On-site,Ireland,56900.0,"Spark, Docker, TensorFlow, SQL, AWS"

In [5]:
import pandas as pd

data_jobs = pd.read_csv("C:\\Users\\Lamees\\Downloads\\data_jobs.csv")
data_jobs.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [10]:
import pandas as pd

jobs = pd.read_parquet("C:\\Users\\Lamees\\Downloads\\jobs-00000-of-00001 (1).parquet")
jobs.to_csv("C:\\Users\\Lamees\\Downloads\\jobs-00000-of-00001 (1).parquet", index=False)
jobs.head()

,company_name,company_domain,company_industry,ats,ats_token,job_id,title,department,location_raw,country,...,employment_type,salary_min,salary_max,salary_currency,salary_period,salary_from_text,skills,posted_at,scraped_at,url
0,0g,landmarkworldwide.com,NaN,ashby,0g,7350655f-4c96-4ceb-9812-e4b42b131559,Chief of Staff,General,Remote,NaN,...,full_time,NaN,NaN,NaN,NaN,False,[],2026-07-13T08:15:50.567+00:00,2026-08-01T01:00:45Z,https://jobs.ashbyhq.com/0g/7350655f-4c96-4ceb...
1,0g,landmarkworldwide.com,NaN,ashby,0g,d35c9785-1912-4c23-8d09-dbbe353d4733,Product Manager — DeFi Products & Applications,Product,Remote,NaN,...,full_time,NaN,NaN,NaN,NaN,False,"[blockchain, product-management, ruby, ui-ux]",2026-07-06T02:01:18.354+00:00,2026-08-01T01:00:45Z,https://jobs.ashbyhq.com/0g/d35c9785-1912-4c23...
2,0g,landmarkworldwide.com,NaN,ashby,0g,8a2f757e-4637-45f4-a453-c88ac205420b,Brand & Creative Designer,Go to Market,Remote,NaN,...,full_time,NaN,NaN,NaN,NaN,False,"[blockchain, communication, figma]",2026-07-15T07:06:18.475+00:00,2026-08-01T01:00:45Z,https://jobs.ashbyhq.com/0g/8a2f757e-4637-45f4...
3,10xteam,NaN,NaN,ashby,10xteam,dc0cf41e-ad58-4ee7-875b-9ebb05294f9b,Surgeon - AI Trainer - Freelance - 8-20 hrs/we...,Healthcare & Medicine,Poland,Poland,...,contract,200.0,250.0,EUR,hour,False,[],2026-05-28T08:44:17.197+00:00,2026-08-01T01:00:45Z,https://jobs.ashbyhq.com/10xteam/dc0cf41e-ad58...
4,10xteam,NaN,NaN,ashby,10xteam,86074cbd-3abf-4afa-95f2-c40ae6ea8c2c,Fractional Chief Information Security Officer ...,"Legal, Compliance & Risk",The Netherlands,Netherlands,...,contract,120.0,180.0,EUR,hour,False,[security],2026-05-28T08:40:20.018+00:00,2026-08-01T01:00:45Z,https://jobs.ashbyhq.com/10xteam/86074cbd-3abf...

In [11]:
#Drop column
fact_job_postings = fact_job_postings.drop(["job_id", "company", "country", "region", "platform", "experience_level", "employment_type", "salary_min_usd", "remote_option", "applicants_estimate", "salary_max_usd"], axis=1)
fact_job_postings.head()

                       job_title posting_date
0           Senior Data Engineer      52:59.3
1                  Data Engineer      52:59.3
2  Business Intelligence Analyst      52:59.3
3                 Data Scientist      52:59.3
4                    AI Engineer      52:59.3

In [12]:
#Drop column
global_ai_ml_jobs_2025 = global_ai_ml_jobs_2025.drop(["Experience Level", "Employment Type", "Company Size", "Work Setting", "Country", "Salary (USD)"], axis=1)
global_ai_ml_jobs_2025.head()

,Year,Job Title,Skills
0,2024,Prompt Engineer,"PyTorch, OpenCV, TensorFlow, Scala"
1,2025,Machine Learning Engineer,"OpenCV, Scala, AWS, Java"
2,2024,Machine Learning Operations (MLOps) Engineer,"Azure, Scikit-learn, Docker, LLMs, PyTorch"
3,2025,Machine Learning Engineer,"Java, OpenCV, PyTorch"
4,2025,Computer Vision Engineer,"Spark, Docker, TensorFlow, SQL, AWS"

In [13]:
#Drop column
data_jobs = data_jobs.drop(["job_title_short", "job_location", "job_via", "job_schedule_type", "job_work_from_home", "search_location", "job_no_degree_mention", "job_health_insurance", "job_country", "salary_rate", "salary_year_avg", "salary_hour_avg", "salary_hour_avg", "company_name"], axis=1)

#Join columns with space
data_jobs["Skills"] = data_jobs["job_skills"] + " " + data_jobs["job_type_skills"]

data_jobs.head()

,job_title,job_posted_date,job_skills,job_type_skills,Skills
0,Senior Clinical Data Engineer / Principal Clin...,2023-06-16 13:44:15,NaN,NaN,NaN
1,Data Analyst,2023-01-14 13:18:07,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...","['r', 'python', 'sql', 'nosql', 'power bi', 't..."
2,"Data Engineer/Scientist/Analyst, Mid or Senior...",2023-10-10 13:14:55,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...","['python', 'sql', 'c#', 'azure', 'airflow', 'd..."
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,2023-07-04 13:01:41,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...","['python', 'c++', 'java', 'matlab', 'aws', 'te..."
4,Data Engineer- Sr Jobs,2023-08-07 14:29:36,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...","['bash', 'python', 'oracle', 'aws', 'ansible',..."

In [14]:
#Drop skill columns as they are all combined in the "Skills" column
data_jobs = data_jobs.drop(["job_skills", "job_type_skills"], axis=1)
data_jobs.head()

,job_title,job_posted_date,Skills
0,Senior Clinical Data Engineer / Principal Clin...,2023-06-16 13:44:15,NaN
1,Data Analyst,2023-01-14 13:18:07,"['r', 'python', 'sql', 'nosql', 'power bi', 't..."
2,"Data Engineer/Scientist/Analyst, Mid or Senior...",2023-10-10 13:14:55,"['python', 'sql', 'c#', 'azure', 'airflow', 'd..."
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,2023-07-04 13:01:41,"['python', 'c++', 'java', 'matlab', 'aws', 'te..."
4,Data Engineer- Sr Jobs,2023-08-07 14:29:36,"['bash', 'python', 'oracle', 'aws', 'ansible',..."

In [15]:
#Drop columns that are not needed
jobs = jobs.drop(["company_name", "company_domain", "company_industry", "ats", "ats_token", "job_id", "department", "location_raw", "country", "employment_type", "salary_min", "salary_max", "salary_currency", "scraped_at", "url"], axis=1)
jobs = jobs.drop(["city", "is_remote", "salary_period", "salary_from_text"], axis=1)
jobs.head()

,title,skills,posted_at
0,Chief of Staff,[],2026-07-13T08:15:50.567+00:00
1,Product Manager — DeFi Products & Applications,"[blockchain, product-management, ruby, ui-ux]",2026-07-06T02:01:18.354+00:00
2,Brand & Creative Designer,"[blockchain, communication, figma]",2026-07-15T07:06:18.475+00:00
3,Surgeon - AI Trainer - Freelance - 8-20 hrs/we...,[],2026-05-28T08:44:17.197+00:00
4,Fractional Chief Information Security Officer ...,[security],2026-05-28T08:40:20.018+00:00

In [16]:
data_jobs_clean = data_jobs.dropna()
data_jobs_clean.head(10)

,job_title,job_posted_date,Skills
1,Data Analyst,2023-01-14 13:18:07,"['r', 'python', 'sql', 'nosql', 'power bi', 't..."
2,"Data Engineer/Scientist/Analyst, Mid or Senior...",2023-10-10 13:14:55,"['python', 'sql', 'c#', 'azure', 'airflow', 'd..."
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,2023-07-04 13:01:41,"['python', 'c++', 'java', 'matlab', 'aws', 'te..."
4,Data Engineer- Sr Jobs,2023-08-07 14:29:36,"['bash', 'python', 'oracle', 'aws', 'ansible',..."
5,GCP Data Engineer,2023-11-07 14:01:59,"['python', 'sql', 'gcp'] {'cloud': ['gcp'], 'p..."
6,Senior Data Engineer - GCP Cloud,2023-03-27 13:18:18,"['sql', 'python', 'java', 'sql server', 'gcp',..."
7,Data Engineer,2023-12-07 13:40:49,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu..."
8,Technology & Operations Business Analyst,2023-06-05 13:44:34,"['excel', 'powerpoint', 'power bi'] {'analyst_..."
9,Data Scientist II,2023-04-23 13:02:57,"['sql', 'python', 'r', 'mongodb', 'mongodb', '..."
10,Erfahrene*r Data Engineer*in (m/w/d),2023-04-17 13:27:32,"['python', 'databricks', 'azure', 'spark'] {'c..."

In [18]:
#Checking how many empty rows exist in the jobs dataset
import numpy as np
empty_count = jobs["skills"].apply(lambda x: isinstance(x, np.ndarray) and x.size == 0).sum()
print("Empty array rows:", empty_count)

Empty array rows: 155048

In [19]:
#Drop rows with empty arrays in skills in the dataset jobs
jobs_clean = jobs[jobs["skills"].apply(lambda x: not (isinstance(x, np.ndarray) and x.size == 0))]

jobs_clean.head(10)

,title,skills,posted_at
1,Product Manager — DeFi Products & Applications,"[blockchain, product-management, ruby, ui-ux]",2026-07-06T02:01:18.354+00:00
2,Brand & Creative Designer,"[blockchain, communication, figma]",2026-07-15T07:06:18.475+00:00
4,Fractional Chief Information Security Officer ...,[security],2026-05-28T08:40:20.018+00:00
6,Senior Accountant / Auditor – AI Trainer - Fre...,[accounting],2026-05-28T08:37:29.326+00:00
9,Project Manager – AI Trainer - Freelance - 8-2...,[project-management],2026-05-28T08:47:26.710+00:00
13,Machine Learning Engineer - AI Trainer - Freel...,"[machine-learning, product-management]",2026-05-28T08:36:20.090+00:00
15,System Operations Engineer - AI Trainer - Free...,[devops],2026-03-15T14:49:53.733+00:00
16,Data Scientist - AI Trainer - Freelance - 8-20...,"[data-science, machine-learning]",2026-05-28T08:39:17.472+00:00
20,Security Architect - AI Trainer - Freelance - ...,[security],2026-05-28T08:22:10.281+00:00
22,Cloud Architect - AI Trainer - Freelance - 8-2...,[devops],2026-04-03T11:58:24.757+00:00

In [20]:
#Rename column names to ensure standardisation
fact_job_postings = fact_job_postings.rename(columns={"job_title": "job_title", "posting_date": "posting_date"})
global_ai_ml_jobs_2025 = global_ai_ml_jobs_2025.rename(columns={"Job Title": "job_title", "Skills": "skills", "Year": "posting_date"})
data_jobs_clean = data_jobs_clean.rename(columns={"job_title": "job_title", "Skills": "skills", "job_posted_date" : "posting_date"})
jobs_clean = jobs_clean.rename(columns={"title": "job_title", "skills": "skills", "posted_at": "posting_date"})

In [21]:
fact_job_postings.head()

                       job_title posting_date
0           Senior Data Engineer      52:59.3
1                  Data Engineer      52:59.3
2  Business Intelligence Analyst      52:59.3
3                 Data Scientist      52:59.3
4                    AI Engineer      52:59.3

In [22]:
global_ai_ml_jobs_2025.head()

,posting_date,job_title,skills
0,2024,Prompt Engineer,"PyTorch, OpenCV, TensorFlow, Scala"
1,2025,Machine Learning Engineer,"OpenCV, Scala, AWS, Java"
2,2024,Machine Learning Operations (MLOps) Engineer,"Azure, Scikit-learn, Docker, LLMs, PyTorch"
3,2025,Machine Learning Engineer,"Java, OpenCV, PyTorch"
4,2025,Computer Vision Engineer,"Spark, Docker, TensorFlow, SQL, AWS"

In [23]:
data_jobs_clean.head()

,job_title,posting_date,skills
1,Data Analyst,2023-01-14 13:18:07,"['r', 'python', 'sql', 'nosql', 'power bi', 't..."
2,"Data Engineer/Scientist/Analyst, Mid or Senior...",2023-10-10 13:14:55,"['python', 'sql', 'c#', 'azure', 'airflow', 'd..."
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,2023-07-04 13:01:41,"['python', 'c++', 'java', 'matlab', 'aws', 'te..."
4,Data Engineer- Sr Jobs,2023-08-07 14:29:36,"['bash', 'python', 'oracle', 'aws', 'ansible',..."
5,GCP Data Engineer,2023-11-07 14:01:59,"['python', 'sql', 'gcp'] {'cloud': ['gcp'], 'p..."

In [24]:
jobs_clean.head()

,job_title,skills,posting_date
1,Product Manager — DeFi Products & Applications,"[blockchain, product-management, ruby, ui-ux]",2026-07-06T02:01:18.354+00:00
2,Brand & Creative Designer,"[blockchain, communication, figma]",2026-07-15T07:06:18.475+00:00
4,Fractional Chief Information Security Officer ...,[security],2026-05-28T08:40:20.018+00:00
6,Senior Accountant / Auditor – AI Trainer - Fre...,[accounting],2026-05-28T08:37:29.326+00:00
9,Project Manager – AI Trainer - Freelance - 8-2...,[project-management],2026-05-28T08:47:26.710+00:00

In [26]:
#Concatenate into one dataset
#Cannot add fact_job_postings dataset as it will give blank values for skills

jobs_all = pd.concat([global_ai_ml_jobs_2025, data_jobs_clean, jobs_clean], ignore_index=True)
jobs_all

,posting_date,job_title,skills
0,2024,Prompt Engineer,"PyTorch, OpenCV, TensorFlow, Scala"
1,2025,Machine Learning Engineer,"OpenCV, Scala, AWS, Java"
2,2024,Machine Learning Operations (MLOps) Engineer,"Azure, Scikit-learn, Docker, LLMs, PyTorch"
3,2025,Machine Learning Engineer,"Java, OpenCV, PyTorch"
4,2025,Computer Vision Engineer,"Spark, Docker, TensorFlow, SQL, AWS"
...,...,...,...
917951,2026-07-03,UI/UX Frontend Developer,[ui-ux]
917952,2026-05-14,US Tax Law AI Specialist (CPA / EA / CA),[accounting]
917953,2026-07-14,VAS validation Engineer - Embedded systems,[embedded]
917954,2026-07-28,Digital Marketing Lead,[marketing]
917955,2026-07-28,Digital Marketing Lead ( Erbil ),[marketing]

In [27]:
#Add fact_job_postings dataset to create one dataset
jobs_all_with_fact_job_postings_dataset = pd.concat([global_ai_ml_jobs_2025, data_jobs_clean, jobs_clean, fact_job_postings], ignore_index=True)
jobs_all_with_fact_job_postings_dataset

,posting_date,job_title,skills
0,2024,Prompt Engineer,"PyTorch, OpenCV, TensorFlow, Scala"
1,2025,Machine Learning Engineer,"OpenCV, Scala, AWS, Java"
2,2024,Machine Learning Operations (MLOps) Engineer,"Azure, Scikit-learn, Docker, LLMs, PyTorch"
3,2025,Machine Learning Engineer,"Java, OpenCV, PyTorch"
4,2025,Computer Vision Engineer,"Spark, Docker, TensorFlow, SQL, AWS"
...,...,...,...
972951,52:59.8,Senior Data Engineer,NaN
972952,52:59.8,Analytics Engineer,NaN
972953,52:59.8,Data Scientist,NaN
972954,52:59.8,Senior Data Analyst,NaN
972955,52:59.8,Analytics Engineer,NaN